// =====================================================================
// SuperCollider Host creation
// =====================================================================

x = SWDataNetwork.new.createHost;
x.makeGui;

// click "View clients" to see all clients that are connected and to which nodes they are subscribed, or which nodes they have created.

// click "View data nodes" to see all the nodes in the network.
